---
- hosts: all
  sudo: true
  vars:
      home: /home/vagrant
      document_root: /vagrant
      os: ubuntu
      osversioncode: trusty
  pre_tasks:
      - name: Symlink sh to bash rather than dash
        file: src=/bin/bash dest=/bin/sh state=link force=true
      - name: Update apt cache and optionally upgrade
        apt:
          update_cache=yes
          cache_valid_time=7200
          #upgrade=yes # Uncomment this to force full upgrade!
      - name: Install stuff from Aptitude
        apt: name={{ item }} state=installed
        with_items:
         - git
         - tig
         - vim
         - gdb
         - cgdb
         - bash-completion # Not included in the docker image
         - make
         - tree
         - htop
         - tmux
         - man-db
  roles:
      - { role: dotfiles, sudo: false }
      - { role: golang, sudo: false }
      #- { role: youcompleteme, sudo: false } # Comment out this to save time!!
      #- { role: mesos, sudo: false }
